### ISSUE TITLE
нужна помощь с дипломным проектом

### ISSUE THREAD

**Issue by dilyarakhabibullina** [dilyarakhabibullina/bookstore#1]
1. Добавление новой книжки работает, но я не пойму, загружается ли текстовый файлик (в папке upload лежит 2.txt, его и пытаюсь грузить.
2. Совсем не получается добавить поиск хотя бы по автору, уже не говоря о поиске внутри файла. Как сделать так, чтобы окно для поиска находилось на главной страничке (/), а результаты- на страничке, например, (/search?)

**Comment by dilyarakhabibullina** [comment]
Добавление новой книжки работает, но я не пойму, загружается ли текстовый файлик (в папке upload лежит 2.txt, его и пытаюсь грузить).
Совсем не получается добавить поиск хотя бы по автору, уже не говоря о поиске внутри файла. При этом сам метод написать удалось. Как сделать так, чтобы окно для поиска находилось на главной страничке (/), а результаты- на страничке, например, (/search?)

**Comment by coursar** [comment]
выложите хотя бы на Heroku - будем смотреть

**Comment by dilyarakhabibullina** [comment]
Выложила, адрес- https://itpark-dilyara708-books1.herokuapp.com/
(также указан в README.md)
